services:
  web-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      # Development: mount local data directory
      - ./data:/app/data
      # Development: enable hot reload (optional)
      - ./src:/src:ro
    restart: no